# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  index: jCompliance
  en: jCompliance
  fr: jCompliance
subtitle:
  en: jcompliance.github.io
  fr: jcompliance.github.io
email: jerome.jsearch@gmail.com
description:
  index: description comes here
  en: description comes here
  fr: description comes here
index:
  en: en.html
  fr: fr.html
feed:
  en: /feed.xml
  fr: /feed-fr.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jcomliance.github.io" # the base hostname & protocol for your site
linkedin_username: jerome-stoessel

# Build settings
markdown: kramdown
