# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  index: jCompliance
  en: jCompliance
  ko: jCompliance
  fr: jCompliance
  zh: jCompliance
  ja: jCompliance
subtitle:
  en: jcompliance.github.io
  ko: jcompliance.github.io
  fr: jcompliance.github.io
  zh: jcompliance.github.io
  ja: jcompliance.github.io
email: jerome.jsearch@gmail.com
description:
  index: description comes here
  en: description comes here
  ko: description comes here
  fr: description comes here
  zh: description comes here
  ja: description comes here
index:
  en: en.html
  ko: ko.html
  fr: fr.html
  zh: zh.html
  ja: ja.html
feed:
  en: /feed.xml
  ko: /feed-ko.xml
  fr: /feed-fr.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.jeann.net" # the base hostname & protocol for your site
linkedin_username: jeannryu
github_username: jeannryu
instagram_username: jeannryu
youtube_username: UCGdBK4vq7JSDxVzCS2lg3Vg
facebook_username: ed2fd709

# Build settings
markdown: kramdown
