# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: blog.jeann.net
  ko: blog.jeann.net
  fr: blog.jeann.net
subtitle:
  en: jeannryu.github.io
  ko: jeannryu.github.io
  fr: jeannryu.github.io
email: jeann.tech@gmail.com
description:
  en:  
  ko:  
  fr: Parce que je viens de commencer à apprendre le français, vous pouvez trouver des erreurs grammaticales dans mon écriture.
index:
  en: 
  ko: kr.html
  fr: fr.html
feed:
  en: /feed.xml
  ko: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.jeann.net" # the base hostname & protocol for your site
linkedin_username: jeannryu
github_username: jeannryu
instagram_username: jeannryu
youtube_username: UCGdBK4vq7JSDxVzCS2lg3Vg
facebook_username: jeannryu

# Build settings
markdown: kramdown
